MCC 172 test functions
======================

====================================  =========================================================
Function                              Description
------------------------------------  ---------------------------------------------------------
:c:func:`mcc172_test_signals_read`    Read the state of the clock, sync, and trigger signals.
:c:func:`mcc172_test_signals_write`   Write values to the clock and sync signals.
====================================  =========================================================
    
.. doxygenfunction:: mcc172_test_signals_read
.. doxygenfunction:: mcc172_test_signals_write
